import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

const poppins = localFont({
  src: "./fonts/Poppins/Poppins-Regular.ttf",
  variable: "--font-poppins-regular",
  weight:"100 900"
})

const bebasNeue = localFont({
  src: "./fonts/Bebas_Neue/BebasNeue-Regular.ttf",
  variable: "--font-bebasNeue-regular",
  weight: "100 900"
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} ${bebasNeue.variable} after:antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
